name: logger_flutter
description: Flutter extension for logger. Please go there for documentation.
version: 1.0.0
author: Simon Leier <simonleier@gmail.com>
homepage: https://github.com/leisim/logger_flutter

environment:
  sdk: '>=2.13.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  logger: ">=1.0.0"
  async: 2.6.1